this.gbar_=this.gbar_||{};(function(_){var window=this;
try{
_.hd=function(a,b,c){if(!a.j)if(c instanceof Array)for(var d of c)_.hd(a,b,d);else{d=(0,_.y)(a.C,a,b);const e=a.v+c;a.v++;b.dataset.eqid=e;a.B[e]=d;b&&b.addEventListener?b.addEventListener(c,d,!1):b&&b.attachEvent?b.attachEvent("on"+c,d):a.o.log(Error("z`"+b))}};
}catch(e){_._DumpException(e)}
try{
_.id=function(){if(!_.q.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{const c=()=>{};_.q.addEventListener("test",c,b);_.q.removeEventListener("test",c,b)}catch(c){}return a}();
}catch(e){_._DumpException(e)}
try{
var jd=document.querySelector(".gb_k .gb_d"),kd=document.querySelector("#gb.gb_Xc");jd&&!kd&&_.hd(_.Sc,jd,"click");
}catch(e){_._DumpException(e)}
try{
var od;_.ld=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.md=function(a,b){if(void 0!==a.i||void 0!==a.j)throw Error("B");a.j=b;_.Jc(a)};_.nd=class extends _.O{constructor(a){super(a)}};od=class extends _.Wc{};_.pd=function(a,b){if(b in a.i)return a.i[b];throw new od;};_.qd=function(a){return _.pd(_.Tc.i(),a)};
}catch(e){_._DumpException(e)}
try{
/*

 SPDX-License-Identifier: Apache-2.0
*/
var wd,Fd,Hd;_.rd=function(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return Number.isFinite(a)?a|0:void 0};_.sd=function(a){const b=a.length;if(0<b){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]};_.ud=function(a){if(a instanceof _.td)return a.i;throw Error("D");};wd=function(a){return new vd(b=>b.substr(0,a.length+1).toLowerCase()===a+":")};
_.yd=function(a,b=_.xd){if(a instanceof _.td)return a;for(let c=0;c<b.length;++c){const d=b[c];if(d instanceof vd&&d.ah(a))return new _.td(a)}};_.Ad=function(a){if(zd.test(a))return a};_.Bd=function(a){return a instanceof _.td?_.ud(a):_.Ad(a)};_.Cd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.Dd=function(a,b,c){return void 0!==_.kb(a,b,c,!1)};_.Ed=function(a,b){return _.rd(_.qc(a,b))};
_.R=function(a,b){a=_.qc(a,b);return null==a?a:Number.isFinite(a)?a|0:void 0};_.S=function(a,b,c=0){return _.lb(_.Ed(a,b),c)};Fd=0;_.Gd=function(a){return Object.prototype.hasOwnProperty.call(a,_.xb)&&a[_.xb]||(a[_.xb]=++Fd)};Hd=function(a){return a};_.Id=function(a){var b=null,c=_.q.trustedTypes;if(!c||!c.createPolicy)return b;try{b=c.createPolicy(a,{createHTML:Hd,createScript:Hd,createScriptURL:Hd})}catch(d){_.q.console&&_.q.console.error(d.message)}return b};
_.Jd=function(a,b){return 0==a.lastIndexOf(b,0)};_.Kd=function(a,b){return Array.prototype.some.call(a,b,void 0)};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var Ld;_.Md=function(){void 0===Ld&&(Ld=_.Id("ogb-qtm#html"));return Ld};var Pd;_.Nd=class{constructor(a){this.i=a}toString(){return this.i+""}};_.Od=function(a){return a instanceof _.Nd&&a.constructor===_.Nd?a.i:"type_error:TrustedResourceUrl"};Pd={};_.Qd=function(a){const b=_.Md();a=b?b.createScriptURL(a):a;return new _.Nd(a,Pd)};_.td=class{constructor(a){this.i=a}toString(){return this.i}};_.Rd=new _.td("about:invalid#zClosurez");var vd,zd;vd=class{constructor(a){this.ah=a}};_.xd=[wd("data"),wd("http"),wd("https"),wd("mailto"),wd("ftp"),new vd(a=>/^[^:]*([/?#]|$)/.test(a))];zd=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;_.Sd={};_.Td=class{constructor(a){this.i=a}toString(){return this.i.toString()}};_.Ud=new _.Td("",_.Sd);_.Vd=RegExp("^[-+,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$");_.Wd=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g");_.Xd=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|radial-gradient|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|steps|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g");_.Yd={};_.$d=function(a){return a instanceof _.Zd&&a.constructor===_.Zd?a.i:"type_error:SafeHtml"};_.Zd=class{constructor(a){this.i=a}toString(){return this.i.toString()}};_.ae=new _.Zd(_.q.trustedTypes&&_.q.trustedTypes.emptyHTML||"",_.Yd);var ce;_.be=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.$d(_.ae);return!b.parentElement});ce=/^[\w+/_-]+[=]{0,2}$/;
_.de=function(a){a=(a||_.q).document;return a.querySelector?(a=a.querySelector('style[nonce],link[rel="stylesheet"][nonce]'))&&(a=a.nonce||a.getAttribute("nonce"))&&ce.test(a)?a:"":""};_.ee=function(a,b){this.width=a;this.height=b};_.m=_.ee.prototype;_.m.aspectRatio=function(){return this.width/this.height};_.m.Fb=function(){return!(this.width*this.height)};_.m.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.m.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.m.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.T=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.fe(c,a,b)[0]||null}return a||null};
_.fe=function(a,b,c){var d;a=c||a;if(a.querySelectorAll&&a.querySelector&&b)return a.querySelectorAll(b?"."+b:"");if(b&&a.getElementsByClassName){var e=a.getElementsByClassName(b);return e}e=a.getElementsByTagName("*");if(b){var f={};for(c=d=0;a=e[c];c++){var g=a.className;"function"==typeof g.split&&_.ua(g.split(/\s+/),b)&&(f[d++]=a)}f.length=d;return f}return e};_.he=function(a){return _.ge(document,a)};
_.ge=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.ie=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.je=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
}catch(e){_._DumpException(e)}
try{
_.ke=function(a){return _.ld(a)&&1==a.nodeType};_.le=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.ie(a),a.appendChild(_.je(a).createTextNode(String(b)))};var me;_.ne=function(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(me||(me={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=me,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)};var re;_.qe=function(a,b,c,d,e,f){if(_.Mb&&e)return _.oe(a);if(e&&!d)return!1;if(!_.Kb){"number"===typeof b&&(b=_.pe(b));var g=17==b||18==b||_.Mb&&91==b;if((!c||_.Mb)&&g||_.Mb&&16==b&&(d||f))return!1}if(_.Lb&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}switch(a){case 13:return _.Kb?f||e?!1:!(c&&d):!0;case 27:return!_.Lb&&!_.Kb}return _.Kb&&(d||e||f)?!1:_.oe(a)};
_.oe=function(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||_.Lb&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:case 171:return _.Kb;default:return!1}};_.pe=function(a){if(_.Kb)a=re(a);else if(_.Mb&&_.Lb)switch(a){case 93:a=91}return a};
re=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};
}catch(e){_._DumpException(e)}
try{
var se,te,ue;se=function(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""};te=function(a){return a.classList?a.classList:se(a).match(/\S+/g)||[]};ue=function(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)};_.U=function(a,b){return a.classList?a.classList.contains(b):_.ua(te(a),b)};_.ve=function(a,b){if(a.classList)a.classList.add(b);else if(!_.U(a,b)){var c=se(a);ue(a,c+(0<c.length?" "+b:b))}};
_.we=function(a,b){if(a.classList)Array.prototype.forEach.call(b,function(e){_.ve(a,e)});else{var c={};Array.prototype.forEach.call(te(a),function(e){c[e]=!0});Array.prototype.forEach.call(b,function(e){c[e]=!0});b="";for(var d in c)b+=0<b.length?" "+d:d;ue(a,b)}};_.xe=function(a,b){a.classList?a.classList.remove(b):_.U(a,b)&&ue(a,Array.prototype.filter.call(te(a),function(c){return c!=b}).join(" "))};
_.ye=function(a,b){a.classList?Array.prototype.forEach.call(b,function(c){_.xe(a,c)}):ue(a,Array.prototype.filter.call(te(a),function(c){return!_.ua(b,c)}).join(" "))};
}catch(e){_._DumpException(e)}
try{
var Be;_.ze=function(a,b){b=_.ta(a,b);let c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};_.Ae=function(a,b,c){for(const d in a)b.call(c,a[d],d,a)};Be=function(a,b){for(const c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Ce=function(a,b){try{return _.Gb(a[b]),!0}catch(c){}return!1};_.Ee=function(a,b){this.type="function"==typeof _.De&&a instanceof _.De?String(a):a;this.currentTarget=this.target=b;this.defaultPrevented=this.i=!1};_.Ee.prototype.stopPropagation=function(){this.i=!0};_.Ee.prototype.preventDefault=function(){this.defaultPrevented=!0};_.Fe=function(a,b){_.Ee.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.timeStamp=0;this.Ta=null;a&&this.init(a,b)};_.A(_.Fe,_.Ee);var Ge={2:"touch",3:"pen",4:"mouse"};
_.Fe.prototype.init=func…